syntax on
highlight Comment ctermfg=Cyan
set number
set nocompatible
set colorcolumn=80
set wildmenu
set ignorecase
set smartcase
set hlsearch
set incsearch
set showmatch
set wrap
set tabstop=2
set background=dark
" Always show statusline
set laststatus=2
" Use 256 colours (Use this setting only if your terminal supports 256 colours)
set t_Co=256
" Always show the command as it is being typed.
set showcmd
" Disable backup files (the ~ files)
set nobackup
set nowritebackup
" Disable persistent undo (the .un~ files)
set noundofile
